language: ruby
rvm:
  - "2.5.0"
sudo: false
cache: bundler
env:
  # http://docs.travis-ci.com/user/environment-variables/#Global-Variables
  global:
    - BITCOINORG_BUILD_TYPE=deployment

before_install:
  - gem update --system
  - gem install bundler

script: make travis

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: travisGHdeploy

  verbose: true
  local-dir: _site/
  repo: thephez.github.io
  target_branch: gh-pages
