language: ruby
rvm:
  - "2.5.0"
sudo: false
cache: bundler
env:
  # http://docs.travis-ci.com/user/environment-variables/#Global-Variables
  global:
    - BITCOINORG_BUILD_TYPE=deployment
    - DOXYFILE: Doxyfile-dashdocs

before_install:
  - gem update --system
  - gem install bundler

# Install dependencies
addons:
  apt:
    packages:
      - flex
      - bison
      - build-essential
      - graphviz

script: make travis

deploy:
  # Set these environment variables in travis-ci.org settings for the repo:
  #
  # GITHUB_TOKEN: token that allows Travis to deploy to GitHub (mark secure)
  # DEPLOY_REPO_NAME: GitHub repo to deploy to (i.e dash-docs/dash-docs.github.io)
  # DEPLOY_TARGET_BRANCH: Branch to deploy to (must be master for page to work correctly)
  #
  # *** NOTE: the target branch is overwritten on deployment. Use caution to
  #       avoid inadvertently overwriting something

  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: travisGHdeploy

  verbose: true
  local-dir: _site/
  repo: $DEPLOY_REPO_NAME
  target_branch: $DEPLOY_TARGET_BRANCH

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x scripts/build-install-doxygen.sh
  - ./scripts/build-install-doxygen.sh
  - chmod +x scripts/generateDocumentationAndDeploy.sh
  - ./scripts/generateDocumentationAndDeploy.sh
